steps:
  - name: node
    entrypoint: yarn
    args: ["install"]
  - name: node
    entrypoint: yarn
    args: ["add", "firebase-tools"]
  - name: node
    entrypoint: yarn
    args: ["build"]
    env: ["_GOOGLE_ANALYTICS_KEY=$_GOOGLE_ANALYTICS_KEY"]
  - name: node
    entrypoint: "./node_modules/.bin/firebase"
    args: ["deploy", "--project", "$PROJECT_ID", "--token", "$_TOKEN"]
